In [5]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [2]:
html = requests.get('https://www.xe.gr/property/results?geo_place_ids%5B%5D=ChIJ8UNwBh-9oRQR3Y1mdkU1Nic&item_type=re_residence&transaction_name=buy').text

In [4]:
soup = BeautifulSoup(html,  "html.parser")
houses = soup.find_all('div', class_ = 'common-property-ad')

for house in houses:
    tm = house.find('div', class_='common-property-ad-title').text
    print(tm)
    price = house.find('div', class_='common-property-ad-price').text.replace(" ", '').replace('|','')
    price = price.strip()
    print(price)
    age = house.find('div', class_='grid-x property-ad-construction-year-container')
    age = str(age)
    age = age.replace('div', '')
    age = age.replace('class=', '')
    age = age.replace('<span>','')
    age = age.replace('</span>','')
    age = age.replace('<i "xe xe-house-construction"></i>', '')
    age = age.replace('</>','')
    age = age.replace('×','')
    age = age.replace('< "grid-x property-ad-construction-year-container">','')
    age = age.strip()
    print("Age: " + age)
    location = house.find('span', class_='common-property-ad-address').text.strip()
    location = location.replace(' | Πώληση κατοικίας', '')
    location = location.replace('Αθήνα (', '')
    location = location.replace(')', '')
    print("Location: " + location)
    rooms = house.find('div', class_='grid-x property-ad-bedrooms-container')
    rooms = str(rooms)
    rooms = rooms.replace('<div class="grid-x property-ad-bedrooms-container">', '')
    rooms = rooms.replace('<i class="xe xe-bedroom"></i>', '')
    rooms = rooms.replace('</div>', '')
    rooms = rooms.replace('<span>', '')
    rooms = rooms.replace('</span>', '')
    rooms = rooms.replace('×', '')
    rooms = rooms.strip()
    print("Rooms: " + rooms)
    bathrooms = house.find('div', class_ = 'grid-x property-ad-bathrooms-container')
    bathrooms = str(bathrooms)
    bathrooms = bathrooms.replace('<div class="grid-x property-ad-bathrooms-container">', '')
    bathrooms = bathrooms.replace('<i class="xe xe-bathroom"></i>', '')
    bathrooms = bathrooms.replace('</div>', '')
    bathrooms = bathrooms.replace('<span>', '')
    bathrooms = bathrooms.replace('</span>', '')
    bathrooms = bathrooms.replace('×', '')
    bathrooms = bathrooms.strip()
    print("Bathrooms: " + bathrooms)
    floor = house.find('span', class_='property-ad-level').text.strip().replace(',','')
    print("Floor: " + str(floor) + "\n--------------------------")

Κτίριο 768 τ.μ.

1.990.000 €


2.591 €/τ.μ.
Age: 2021
Location: Ηπείρου
Rooms: 16
Bathrooms: 15
Floor: Υπόγειο
--------------------------

Διαμέρισμα 68 τ.μ.

230.000 €


3.382 €/τ.μ.
Age: 2008
Location: Νέα Κυψέλη
Rooms: 2
Bathrooms: 1
Floor: 2ος
--------------------------

Διαμέρισμα 82 τ.μ.

450.000 €


5.488 €/τ.μ.
Age: 2000
Location: Παναθηναϊκό Στάδιο
Rooms: 2
Bathrooms: 1
Floor: 4ος
--------------------------

Διαμέρισμα 66 τ.μ.

110.000 €


1.667 €/τ.μ.
Age: 1962
Location: Ερυθρός
Rooms: 1
Bathrooms: 1
Floor: 2ος
--------------------------

Διαμέρισμα 54 τ.μ.

65.000 €


1.204 €/τ.μ.
Age: 1978
Location: Ακαδημία Πλάτωνος
Rooms: 1
Bathrooms: 1
Floor: Υπερυψωμένο
--------------------------

Διαμέρισμα 100 τ.μ.

270.000 €


2.700 €/τ.μ.
Age: 1960
Location: Πεδίον Άρεως
Rooms: 2
Bathrooms: 1
Floor: 4ος
--------------------------

Διαμέρισμα 72 τ.μ.

200.000 €


2.778 €/τ.μ.
Age: 1965
Location: Παναθηναϊκό Στάδιο
Rooms: 2
Bathrooms: 1
Floor: 3ος
--------------------------

Διαμέρισμα 85 τ.μ.

80.000 €


941 €/τ.μ.
Age: 1970
Location: Πλατεία Βικτωρίας
Rooms: 2
Bathrooms: 1
Floor: 6ος
--------------------------

Διαμέρισμα 98 τ.μ.

530.000 €


5.408 €/τ.μ.
Age: None
Location: Λυκαβηττός
Rooms: 3
Bathrooms: 2
Floor: 2ος
--------------------------

Διαμέρισμα 54 τ.μ.

98.000 €


1.815 €/τ.μ.
Age: 1977
Location: Άνω Πετράλωνα
Rooms: 1
Bathrooms: 1
Floor: 2ος
--------------------------

Διαμέρισμα 40 τ.μ.

120.000 €


3.000 €/τ.μ.
Age: 2003
Location: Γούβα
Rooms: 1
Bathrooms: None
Floor: 4ος
--------------------------

Διαμέρισμα 100 τ.μ.

150.000 €


1.500 €/τ.μ.
Age: None
Location: Πλατεία Αττικής
Rooms: 2
Bathrooms: 1
Floor: 5ος
--------------------------

Διαμέρισμα 89 τ.μ.

320.000 €


3.596 €/τ.μ.
Age: 2010
Location: Άγιος Αρτέμιος
Rooms: 3
Bathrooms: 1
Floor: 7ος
--------------------------

Μεζονέτα 75 τ.μ.

235.000 €


3.121 €/τ.μ.
Age: 2023
Location: Κάτω Πετράλωνα
Rooms: 1
Bathrooms: 1
Floor: 3ος
--------------------------

Διαμέρισμα 75 τ.μ.

105.000 €


1.400 €/τ.μ.
Age: 2005
Location: Σεπόλια
Rooms: 2
Bathrooms: 1
Floor: 1ος
--------------------------

Διαμέρισμα 44 τ.μ.

75.000 €


1.705 €/τ.μ.
Age: 1965
Location: Κολωνός
Rooms: 1
Bathrooms: 1
Floor: 2ος
--------------------------

Διαμέρισμα 189 τ.μ.

500.000 €


2.646 €/τ.μ.
Age: 1975
Location: Λόφος Σκουζέ
Rooms: 6
Bathrooms: 2
Floor: Ημιώροφος
--------------------------

Διαμέρισμα 74 τ.μ.

280.000 €


3.784 €/τ.μ.
Age: 1971
Location: Ιπποκράτειο
Rooms: 2
Bathrooms: 2
Floor: 3ος
--------------------------

Διαμέρισμα 75 τ.μ.

130.000 €


1.733 €/τ.μ.
Age: 1970
Location: Ανάληψη
Rooms: 2
Bathrooms: 1
Floor: 3ος
--------------------------

Διαμέρισμα 90 τ.μ.

120.000 €


1.333 €/τ.μ.
Age: None
Location: Ηπείρου
Rooms: 2
Bathrooms: 1
Floor: 2ος
--------------------------

Διαμέρισμα 66 τ.μ.

125.000 €


1.894 €/τ.μ.
Age: 1970
Location: Κυψέλη
Rooms: 2
Bathrooms: 2
Floor: 6ος
--------------------------

Κτίριο 806 τ.μ.

720.000 €


893 €/τ.μ.
Age: None
Location: Πλατεία Βάθης
Rooms: 7
Bathrooms: 7
Floor: Υπόγειο
--------------------------

Διαμέρισμα 50 τ.μ.

73.000 €


1.460 €/τ.μ.
Age: 1963
Location: Κολωνός
Rooms: 1
Bathrooms: 1
Floor: 3ος
--------------------------

Διαμέρισμα 148 τ.μ.

120.000 €


811 €/τ.μ.
Age: 1975
Location: Ακαδημία Πλάτωνος
Rooms: 3
Bathrooms: 1
Floor: 3ος
--------------------------

Μεζονέτα 100 τ.μ.

250.000 €


2.500 €/τ.μ.
Age: 1969
Location: Νέα Φιλοθέη
Rooms: 2
Bathrooms: 2
Floor: 2ος
--------------------------

Διαμέρισμα 105 τ.μ.

225.000 €


2.143 €/τ.μ.
Age: 1970
Location: Αμπελόκηποι
Rooms: 3
Bathrooms: 1
Floor: 4ος
--------------------------

Κτίριο 600 τ.μ.

1.000.000 €


1.667 €/τ.μ.
Age: 1985
Location: Πολύγωνο
Rooms: 15
Bathrooms: 12
Floor: Υπόγειο
--------------------------

Διαμέρισμα 89 τ.μ.

320.000 €


3.596 €/τ.μ.
Age: 2010
Location: Άγιος Ιωάννης
Rooms: 3
Bathrooms: 1
Floor: 7ος
--------------------------

Διαμέρισμα 30 τ.μ.

56.000 €


1.867 €/τ.μ.
Age: 1975
Location: Πλατεία Αττικής
Rooms: 1
Bathrooms: 1
Floor: Υπερυψωμένο
--------------------------

Διαμέρισμα 51 τ.μ.

57.000 €


1.118 €/τ.μ.
Age: 1960
Location: Άνω Πετράλωνα
Rooms: 1
Bathrooms: 1
Floor: Ισόγειο
--------------------------

Διαμέρισμα 71 τ.μ.

160.000 €


2.254 €/τ.μ.
Age: 1965
Location: Πλατεία Βικτωρίας
Rooms: 2
Bathrooms: 1
Floor: 5ος
--------------------------

Διαμέρισμα 71 τ.μ.

125.000 €


1.761 €/τ.μ.
Age: 1970
Location: Σεπόλια
Rooms: 2
Bathrooms: 1
Floor: 5ος
--------------------------

Διαμέρισμα 104 τ.μ.

190.000 €


1.827 €/τ.μ.
Age: 1922
Location: Λόφος Σκουζέ
Rooms: 3
Bathrooms: 1
Floor: Ισόγειο
--------------------------

Διαμέρισμα 58 τ.μ.

115.000 €


1.983 €/τ.μ.
Age: 1982
Location: Πολύγωνο
Rooms: 2
Bathrooms: 1
Floor: 3ος
--------------------------

In [ ]:
"""
page 4
https://www.xe.gr/property/results?geo_place_ids%5B%5D=ChIJ8UNwBh-9oRQR3Y1mdkU1Nic&item_type=re_residence&transaction_name=buy&page=4
"""

In [7]:
df = pd.DataFrame({'Area':tm,'Price':price,'Age':age,'Location':location,'Rooms':rooms,'Bathrooms':bathrooms}, index=[0]) 
df.to_csv('houses.csv', index=True, encoding='utf-8')

In [8]:
df

,Area,Price,Age,Location,Rooms,Bathrooms
0,\nΔιαμέρισμα 58 τ.μ.\n,115.000 €\n\n\n1.983 €/τ.μ.,1982,Πολύγωνο,2,1